---
title: "Identifying hotspots of plant species range limits across California"
output: rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load and/or install required packages
```{r setup}
## Identify required package names
### CRAN packages
cran_packages <- c("tidyverse", "sf", "terra", "tmap")
## Install CRAN packages not yet installed
installed_cran_packages <- cran_packages %in% rownames(installed.packages())
if (any(installed_cran_packages == FALSE)) {
  install.packages(cran_packages[!installed_cran_packages])
}
## Load all packages
invisible(lapply(cran_packages, library, character.only = TRUE))
```

# Get geographical boundary layers
```{r, include = FALSE, echo = FALSE}
## Get California boundary
ca_boundary <- USA.state.boundaries::state_boundaries_wgs84[USA.state.boundaries::state_boundaries_wgs84$STATE_ABBR == "CA", ]
## Get Dangermond Preserve boundary
dangermond_preserve <- esri2sf::esri2sf("https://services.arcgis.com/F7DSX1DSNSiWmOqh/arcgis/rest/services/jldp_boundary/FeatureServer/2")
```

# Load plant species distribution models from Kling et al. (2018) and calculate plant range limits
# downloaded from https://github.com/matthewkling/facets-of-phylodiversity/releases/tag/data810m
```{r, include = FALSE, echo = FALSE}
source("~/calculate_range_limit_probabilities.R")
# download function from GitHub repository: https://raw.githubusercontent.com/elimia-analytics/Dangermond-Biodiversity/refs/heads/main/calculate_range_limit_probabilities.R
dir.create("plant_range_limit_rasters")
model_files <- list.files("data/Kling_et_al_2018", full.names = TRUE)
future::plan("multisession", workers = 3)
furrr::future_map(model_files[1:length(model_files)], function(mod){
  prob_raster <- terra::rast(mod)
  prob_raster <- terra::aggregate(prob_raster, 2)
  r <- prob_raster
  values(r)[which(values(r) == 0)] <- NA
  r <- r %>% terra::trim()
  # Calculate plant northern range limits
  if (terra::ymax(r) <= (ymax(prob_raster)-10000)){
    n_edge_raster <- calculate_range_limit_probabilities(probability_raster = prob_raster, limit = "northern")
    terra::writeRaster(n_edge_raster$latitudinal_probability_raster, paste0("plant_range_limit_rasters/", prob_raster %>% names(), "_northern_probability.tif"), overwrite = TRUE)
    terra::writeRaster(n_edge_raster$edge_raster, paste0("plant_range_limit_rasters/", prob_raster %>% names(), "_northern_edge_limit.tif"), overwrite = TRUE)
  }
  # Calculate plant southern range limits
  if (terra::ymin(r) >= (ymin(prob_raster)+10000)){
    s_edge_raster <- calculate_range_limit_probabilities(probability_raster = prob_raster, limit = "southern")
    terra::writeRaster(s_edge_raster$latitudinal_probability_raster, paste0("plant_range_limit_rasters/", prob_raster %>% names(), "_southern_probability.tif"), overwrite = TRUE)    
    terra::writeRaster(s_edge_raster$edge_raster, paste0("plant_range_limit_rasters/", prob_raster %>% names(), "_southern_edge_limit.tif"), overwrite = TRUE)
  }
    rm(s_edge_raster, n_edge_raster)
  gc()
  NULL
})
```

## Quantify range limit hotspots
```{r, include = FALSE, echo = FALSE}
### Southern range limit hotspots
southern_edge_limit_files <- list.files("plant_range_limit_rasters", pattern = "southern_edge_limit.tif", full.names = TRUE)
southern_edge_limit_rasters <- terra::rast(purrr::map(southern_edge_limit_files, terra::rast))
southern_edge_limit_hotspots <- terra::app(southern_edge_limit_rasters, sum, na.rm = TRUE)
southern_edge_limit_hotspots %>% terra::writeRaster("california_plant_range_southern_edge_hotspots.tif", overwrite = TRUE)

### Northern range limits hotspots
northern_edge_limit_files <- list.files("plant_range_limit_rasters", pattern = "northern_edge_limit.tif", full.names = TRUE)
northern_edge_limit_rasters <- terra::rast(purrr::map(northern_edge_limit_files, terra::rast))
northern_edge_limit_hotspots <- terra::app(northern_edge_limit_rasters, sum, na.rm = TRUE)
northern_edge_limit_hotspots %>% terra::writeRaster("california_plant_range_northern_edge_hotspots.tif", overwrite = TRUE)

```

## Quantify latitudinal limit hotspots
```{r, include = FALSE, echo = FALSE}
### Southern latitudinal limit hotspots
southern_latitude_limit_files <- list.files("plant_range_limit_rasters", pattern = "southern_probability.tif", full.names = TRUE)
southern_latitude_limit_rasters <- terra::rast(purrr::map(southern_latitude_limit_files, terra::rast))
southern_latitude_limit_hotspots <- terra::app(southern_latitude_limit_rasters, sum, na.rm = TRUE)
southern_latitude_limit_hotspots %>% terra::writeRaster("california_plant_southern_latitude_limit_hotspots.tif", overwrite = TRUE)
### Northern latitudinal limit hotspots
northern_latitude_limit_files <- list.files("plant_range_limit_rasters", pattern = "northern_probability.tif", full.names = TRUE)
northern_latitude_limit_rasters <- terra::rast(purrr::map(northern_latitude_limit_files, terra::rast))
northern_latitude_limit_hotspots <- terra::app(northern_latitude_limit_rasters, sum, na.rm = TRUE)
northern_latitude_limit_hotspots %>% terra::writeRaster("california_plant_northern_latitude_limit_hotspots.tif", overwrite = TRUE)
```

## Map range/latitudinal limit hotspots
```{r, include = FALSE, echo = FALSE}


## Illustration of latitudinal limit quantification
## Generate static maps
d_vect <- dangermond_preserve %>% 
  sf::st_transform(st_crs(southern_edge_limit_hotspots)) %>% 
  terra::vect()
d_bbox <- southern_edge_limit_hotspots %>% 
  terra::crop(d_vect) %>% 
  terra::extend(15)
d_bbox2 <- southern_edge_limit_hotspots %>% 
  terra::crop(d_vect) %>% 
  terra::extend(100)
## Illustration of latitudinal limit calculation
latitudinal_limit_r <- southern_latitude_limit_rasters[[8]] %>%
  terra::crop(d_bbox2)
#### California
png(filename = "output/latitudinal_limit_calculation_illustration.png")
terra::plot(latitudinal_limit_r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
## Illustration of range edge calculation
edge_r <- southern_edge_limit_rasters[[8]] %>%
  terra::crop(d_bbox2)
png(filename = "output/range_edge_calculation_illustration.png")
terra::plot(edge_r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
### Southern Range Limit Hotspots
#### California
png(filename = "output/california_plant_range_southern_edge_hotspots.png")
terra::plot(southern_edge_limit_hotspots, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
#### Dangermond Preserve
png(filename = "output/dangermond_plant_range_southern_edge_hotspots.png")
r <- southern_edge_limit_hotspots %>% 
  terra::crop(d_bbox)
terra::plot(r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
terra::plot(d_vect, add = TRUE)
dev.off()
### Southern Latitudinal Limit Hotspots
#### California
png(filename = "output/california_plant_southern_latitude_limit_hotspots.png")
terra::plot(southern_latitude_limit_hotspots, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
#### Dangermond Preserve
png(filename = "output/dangermond_plant_southern_latitude_limit_hotspots.png")
r <- southern_latitude_limit_hotspots %>% 
  terra::crop(d_bbox)
terra::plot(r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
terra::plot(d_vect, add = TRUE)
dev.off()
### Northern Range Limit Hotspots
#### California
png(filename = "output/california_plant_range_northern_edge_hotspots.png")
terra::plot(northern_edge_limit_hotspots, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
#### Dangermond Preserve
png(filename = "output/dangermond_plant_range_northern_edge_hotspots.png")
r <- northern_edge_limit_hotspots %>% 
  terra::crop(d_bbox)
terra::plot(r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
terra::plot(d_vect, add = TRUE)
dev.off()
### Northern Latitudinal Limit Hotspots
#### California
png(filename = "output/california_plant_northern_latitude_limit_hotspots.png")
terra::plot(northern_latitude_limit_hotspots, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
dev.off()
#### Dangermond Preserve
png(filename = "output/dangermond_plant_northern_latitude_limit_hotspots.png")
r <- northern_latitude_limit_hotspots %>% 
  terra::crop(d_bbox)
terra::plot(r, axes = FALSE, box = FALSE, col = RColorBrewer::brewer.pal(9, "Spectral"))
terra::plot(d_vect, add = TRUE)
dev.off()
### Generate interactive map
library(leaflet)
col_pal1 <- colorNumeric("Spectral", values(southern_edge_limit_hotspots), na.color = "transparent")
col_pal2 <- colorNumeric("Spectral", values(southern_latitude_limit_hotspots), na.color = "transparent")
col_pal3 <- colorNumeric("Spectral", values(northern_edge_limit_hotspots), na.color = "transparent")
col_pal4 <- colorNumeric("Spectral", values(northern_latitude_limit_hotspots), na.color = "transparent")
legend_pal <- colorNumeric("Spectral", seq(0, 1, 0.1), na.color = "transparent")

m <- leaflet::leaflet(options = leafletOptions(zoomDelta = 0.5, zoomSnap = 0, attributionControl = FALSE)) %>% # Open new leaflet web map
    leaflet::setView(lng = -120, lat = 37.5, zoom = 6) %>%  # Zoom in on North America
    leaflet::addMapPane("basemap1", zIndex = -100) %>% # Add basemap 1
    leaflet::addProviderTiles(providers$Esri.WorldTerrain, group = "Esri World Terrain", options = list(pathOptions(pane = "basemap1"))) %>%
    leaflet::addScaleBar(position = "bottomleft") %>% # Add scale bar
    leaflet.extras::addResetMapButton() %>% # Add button to reset map bounds
    leaflet::addLayersControl(baseGroups = c("Esri World Terrain"),
                              overlayGroups = c("Southern Range Limit Hotspots",
                                                   "Southern Latitudinal Limit Hotspots",
                                                   "Northern Range Limit Hotspots",
                                                   "Northern Latitudinal Limit Hotspots"),
                              options = layersControlOptions(collapsed = TRUE), position = "topleft") %>% 
        leaflet::addMapPane("southern_range", zIndex = 400) %>%
      leaflet::addRasterImage(
        x = southern_edge_limit_hotspots %>% terra::project("epsg:3857"),
        colors = col_pal1,
        opacity = 0.9,
        project = FALSE,
        group = "Southern Range Limit Hotspots",
        maxBytes = Inf,
        options = leaflet::pathOptions(pane = "southern_range")
      ) %>% 
      leaflet::addMapPane("southern_latitude", zIndex = 400) %>%
      leaflet::addRasterImage(
        x = southern_latitude_limit_hotspots %>% terra::project("epsg:3857"),
        colors = col_pal2,
        opacity = 0.9,
        project = FALSE,
        group = "Southern Latitudinal Limit Hotspots",
        maxBytes = Inf,
        options = leaflet::pathOptions(pane = "southern_latitude")
      ) %>% 
          leaflet::addMapPane("northern_range", zIndex = 400) %>%
      leaflet::addRasterImage(
        x = northern_edge_limit_hotspots %>% terra::project("epsg:3857"),
        colors = col_pal3,
        opacity = 0.9,
        project = FALSE,
        group = "Northern Range Limit Hotspots",
        maxBytes = Inf,
        options = leaflet::pathOptions(pane = "northern_range")
      ) %>% 
      leaflet::addMapPane("northern_latitude", zIndex = 400) %>%
      leaflet::addRasterImage(
        x = northern_latitude_limit_hotspots %>% terra::project("epsg:3857"),
        colors = col_pal4,
        opacity = 0.9,
        project = FALSE,
        group = "Northern Latitudinal Limit Hotspots",
        maxBytes = Inf,
        options = leaflet::pathOptions(pane = "northern_latitude")
      ) %>%
      leaflet::addLegend(pal = legend_pal, values = seq(0, 1, 0.1), labels = c(""), position = "bottomleft") %>%  # Add legend to describe layers to be mapped
leaflet::hideGroup("Southern Latitudinal Limit Hotspots") %>% 
leaflet::hideGroup("Northern Range Limit Hotspots") %>%
leaflet::hideGroup("Northern Latitudinal Limit Hotspots")

m

```
